import Head from 'next/head'
import { useTheme } from '../lib/themecontext'
import styles from '../styles/Home.module.css'

import { getCountries } from '../lib/countries'

import Navbar from '../components/navbar/navbar'
import InputSearch from '../components/input-search/input-search'
import SelectRegion from '../components/select-region/select-region'

export default function Home() {
  const { theme } = useTheme()
  const test = async () => {
    const response = await getCountries();
    console.log(response)
  }

  test()
  return (
    <div className={styles.container+" "+theme}>
      <Head>
        <title>Frontend Mentor | Rest Countries API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"></link>
      </Head>

      <header className={styles.header}>
        <Navbar />
      </header>
      <main className={styles.main}>
        <section className={styles.searchbar}>
          <InputSearch />
          <SelectRegion />
        </section>
        <section className={styles.list_countries}>
        </section>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

